name: AWS DEPLOY TO STAGING
# turn off deploy to AWS

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PW: ${{ secrets.DB_PW}}
      DB_USER: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_NAME }}
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
      FIREBASE_PRIVATE_KEY_ID: ${{secrets.FIREBASE_PRIVATE_KEY_ID}}
      FIREBASE_PRIVATE_KEY: ${{secrets.FIREBASE_PRIVATE_KEY}}
      FIREBASE_CLIENT_EMAIL: ${{secrets.FIREBASE_CLIENT_EMAIL}}
      FIREBASE_CLIENT_ID: ${{secrets.FIREBASE_CLIENT_ID}}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install

      - run: |
          touch .env
          echo DB_HOST = "$DB_HOST" >> .env
          echo DB_PW = "$DB_PW" >> .env
          echo DB_USER = "$DB_USER" >> .env
          echo DB_NAME = "$DB_NAME" >> .env
          echo PORT = "3031" >> .env
          echo CLIENT_ID = "$CLIENT_ID" >> .env
          echo CLIENT_SECRET = "$CLIENT_SECRET" >> .env
          echo FIREBASE_PROJECT_ID = "$FIREBASE_PROJECT_ID" >> .env
          echo FIREBASE_PRIVATE_KEY_ID = "$FIREBASE_PRIVATE_KEY_ID" >> .env
          echo FIREBASE_PRIVATE_KEY = "$FIREBASE_PRIVATE_KEY" >> .env
          echo FIREBASE_CLIENT_EMAIL = "$FIREBASE_CLIENT_EMAIL" >> .env
          echo FIREBASE_CLIENT_ID = "$FIREBASE_CLIENT_ID" >> .env

      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deploy/"
          REMOTE_HOST: "flightplan.eaglesoftwareteam.com"
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/2025/flight-plan/t1"
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: "ubuntu@flightplan.eaglesoftwareteam.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            cd nodeapps/2025/flight-plan/t1
            npm install
            sudo systemctl stop flight-plan-t1-backend.service
            sudo cp flight-plan-t1-backend.service /lib/systemd/system/flight-plan-t1-backend.service
            sudo systemctl daemon-reload
            sudo systemctl start flight-plan-t1-backend
