name: Deploy to Windows Dev

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  windows-deploy:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    env:
      DB_HOST: ${{ secrets.DEV_DB_HOST }}
      DB_PW: ${{ secrets.DEV_DB_PW}}
      DB_USER: ${{ secrets.DEV_DB_USER }}
      DB_NAME: ${{ secrets.DEV_DB_NAME }}
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
      FIREBASE_PRIVATE_KEY_ID: ${{secrets.FIREBASE_PRIVATE_KEY_ID}}
      FIREBASE_PRIVATE_KEY: ${{secrets.FIREBASE_PRIVATE_KEY}}
      FIREBASE_CLIENT_EMAIL: ${{secrets.FIREBASE_CLIENT_EMAIL}}
      FIREBASE_CLIENT_ID: ${{secrets.FIREBASE_CLIENT_ID}}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - run: |
          
          echo DB_HOST=${{env.DB_HOST}} > .env
          echo DB_PW=${{env.DB_PW}} >> .env
          echo DB_USER=${{env.DB_USER}} >> .env
          echo DB_NAME=${{env.DB_NAME}} >> .env
          echo CLIENT_ID=${{env.CLIENT_ID}} >> .env
          echo CLIENT_SECRET=${{env.CLIENT_SECRET}} >> .env
          echo FIREBASE_PROJECT_ID=${{secrets.FIREBASE_PROJECT_ID}} >> .env
          echo FIREBASE_PRIVATE_KEY_ID=${{secrets.FIREBASE_PRIVATE_KEY_ID}} >> .env
          echo FIREBASE_PRIVATE_KEY=${{secrets.FIREBASE_PRIVATE_KEY}} >> .env
          echo FIREBASE_CLIENT_EMAIL=${{secrets.FIREBASE_CLIENT_EMAIL}} >> .env
          echo FIREBASE_CLIENT_ID=${{secrets.FIREBASE_CLIENT_ID}} >> .env

      - run: npm run winbundle

      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: deploy/
          remote: c:/nodeapps/flightplan-backend
          recursive: true
          host: "flightplandev.oc.edu"
          username: "david.north"
          privateKey: ${{ secrets.DEV_WIN_SERVER_SSH_KEY  }}
          password: ${{ secrets.PASSWORD }}

      - name: Command via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: '.\deploy-flightplan-backend'
          host: "flightplandev.oc.edu"
          username: "david.north"
          privateKey: ${{ secrets.DEV_WIN_SERVER_SSH_KEY  }}
